version: "2"
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - CACHE_PATH=/cache/
      - DATA_PATH=/data/
      - USERNAME
      - PASSWORD
      - DATABASE
      - MONGO_HOST
      - MONGO_DATABASE
      - MONGO_USERNAME
      - MONGO_PASSWORD
      - MONGO_PORT
    volumes:
      - ${DATA_DIR}:/data/
      - ${CACHE_DIR}:/cache/
    ports:
      - "${PORT}:3523"
