version: '3'
services:
  primary:
    image: simplyboo6/vimtur:latest
    ports:
      - "3523:3523"
    environment:
      - DATA_PATH=/data/media
      - CACHE_PATH=/data/cache
      - DATABASE=mongodb
      - DATABASE_URI=mongodb://mongo
      - DATABASE_DB=vimtur
      - PORT=3523
    volumes:
      - "${DATA_DIR}:/data/media"
      - "${CACHE_DIR}:/data/cache"

  mongo:
    image: mongo
    volumes:
      - ${CACHE_DIR}/mongo:/data/db