version: '3'
services:
  vimtur:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - CACHE_PATH=/cache/
      - DATA_PATH=/data/
      - USERNAME
      - PASSWORD
      - DATABASE
      - DATABASE_URI
      - DATABASE_DB
    volumes:
      - ${DATA_DIR}:/data/
      - ${CACHE_DIR}:/cache/
    ports:
      - '${PORT}:3523'
  mongo:
    image: mongo
    volumes:
      - ${CACHE_DIR}/mongo:/data/db
